version: '3.2'
services:
    kepler:
        image: ewout/kepler:1.1.21
        restart: always
        environment:
            KEPLER_BIND: 0.0.0.0
            KEPLER_RCON_BIND: 0.0.0.0
            MYSQL_HOST: mariadb
            MYSQL_PORT: 3306
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
        depends_on:
            - mariadb
        links:
            - mariadb
        expose:
            - "12321"
            - "12309"
        ports:
            - "12322:12322"
            - "12321:12321"

    matcha:
        image: ewout/matcha:0.1.8
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_PORT: 3306
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
            REDIS_HOST: redis
            REDIS_PORT: 6379
            KEPLER_INTERNAL_HOST: kepler
            KEPLER_EXTERNAL_HOST: beta.oldhabbo.com
            KEPLER_RCON_PORT: 12309
        depends_on:
            - redis
        links:
            - redis
            - kepler
        expose:
            - "9000"
        ports:
            - "127.0.0.1:12316:9000"

    redis:
        image: redis:4
        restart: always
        volumes:
            - redis-data:/data

    mariadb:
        image: mariadb:10
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: superverysecret
            MYSQL_DATABASE: kepler
            MYSQL_USER: kepler
            MYSQL_PASSWORD: verysecret
        volumes:
            - kepler-data:/var/lib/mysql
        ports:
            - "127.0.0.1:3307:3306"
volumes:
    kepler-data:
    redis-data:
